require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, '16.0'
use_modular_headers!

target 'PawCoin' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  # Use frameworks if specified in podfile_properties or ENV
  linkage = nil

  if podfile_properties['ios.useFrameworks'].is_a?(String) && ['static', 'dynamic'].include?(podfile_properties['ios.useFrameworks'])
    linkage = podfile_properties['ios.useFrameworks'].to_sym
  elsif podfile_properties['ios.useFrameworks'] == true || podfile_properties['ios.useFrameworks'] == 'true'
    linkage = true
  elsif ENV['USE_FRAMEWORKS'].is_a?(String) && ['static', 'dynamic'].include?(ENV['USE_FRAMEWORKS'])
    linkage = ENV['USE_FRAMEWORKS'].to_sym
  elsif ENV['USE_FRAMEWORKS'] == true || ENV['USE_FRAMEWORKS'] == 'true'
    linkage = true
  end

  if linkage.is_a?(Symbol)
    use_frameworks! :linkage => linkage
  elsif linkage == true
    use_frameworks!
  end

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  pod 'gRPC-C++', '~> 1.69.0'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
